
version: "3.8"
services:
  dashy:
    image: lissy93/dashy:latest
    container_name: Dashy
    ports:
      - 8080:8080
    volumes:
      - ./conf.yml:/app/user-data/conf.yml
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
